spring:
  datasource:
    url: jdbc:mysql://${mysql.server.host}:${mysql.server.port}/${mysql.database}?useSSL=false&verifyServerCertificate=false&requireSSL=false
    username: ${mysql.user}
    password: ${mysql.password}
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: create
    # hibernate.ddl-auto: update
    # hibernate.ddl-auto: validate
    # properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    # database-platform: MYSQL
    # database: MYSQL
