FROM openjdk:8u131-jre-alpine
RUN apk --no-cache add busybox-suid bash \
  && addgroup app-group \
  && adduser -h /home/app -s /bin/bash -D -u 1025 app app-group
#Usage: adduser [OPTIONS] USER [GROUP]
#
#Create new user, or add USER to GROUP
#
#        -h DIR          Home directory
#        -g GECOS        GECOS field
#        -s SHELL        Login shell
#        -G GRP          Add user to existing group
#        -S              Create a system user
#        -D              Don't assign a password
#        -H              Don't create home directory
#        -u UID          User id
#        -k SKEL         Skeleton directory (/etc/skel)
WORKDIR /home/app
USER app
COPY build/libs/*.jar /home/app/app.jar
EXPOSE 8080
ENTRYPOINT sh -c "java \
-Xss228k -Xms128m -Xmx256m -XX:MaxMetaspaceSize=128M \
-XX:MaxDirectMemorySize=128M -Dserver.tomcat.max-threads=1 \
-Djava.security.egd=file:/dev/./urandom -jar /home/app/app.jar"
